version: '3'
services:
### phpfpm ###########################################
    php-fpm:
        build:
            context: ./
            dockerfile: ./docker/php-fpm/Dockerfile
            target: local
        environment:
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        ports:
            - 9000:9000
        volumes:
            - .:/var/www
            - /var/www/vendor/
            - ./docker/php-fpm/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        restart: always
        networks:
            - sail
### nginx ###########################################
    nginx:
        build:
            context: ./docker/nginx
        ports:
            - '${APP_PORT:-80}:80'
        restart: always
        volumes:
            - ./public:/var/www/public
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - sail
        depends_on:
            - php-fpm
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
