version: '3.8'

services:
### dashy ###########################################
    dashy:
        image: 'lissy93/dashy'
        ports:
            - '8080:80'
        volumes:
            - ./docker/dashy/conf.yml:/app/public/conf.yml
### Mysql ###########################################
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
### Redis ###########################################
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
### phpMyAdmin ######################
    phpmyadmin:
        build: ./docker/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        ports:
            - "${SAIL_PMA_PORT}:80"
        depends_on:
            - mysql
        networks:
            - sail
### phpRedisAdmin ######################
    phpredisadmin:
        image: erikdubbelboer/phpredisadmin
        environment:
            - REDIS_1_HOST=${REDIS_HOST}
            - REDIS_1_PORT=${REDIS_PORT}
            - ADMIN_USER=${REDIS_ADMIN_USER}
            - ADMIN_PASS=${REDIS_ADMIN_PASS}
        ports:
            - "${REDIS_ADMIN_PORT}:80"
        networks:
            - sail
### elasticsearch ######################
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
        container_name: es01
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - xpack.security.enabled=false
        ports:
            - 9200:9200
        networks:
            - sail
### kibana ######################
    kibana:
        image: docker.elastic.co/kibana/kibana:8.6.2
        container_name: kib-01
        ports:
            - 5601:5601
        networks:
            - sail
### metricbeat #####################
    metricbeat:
        image: docker.elastic.co/beats/metricbeat:8.6.2
        environment:
          - ELASTICSEARCH_HOST=elasticsearch
          - KIBANA_HOST=kibana
          #- ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
          #- ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
        networks:
            - sail
